version: '3.8'

services:
  db:
    container_name: db
    image: "postgres:10.18-alpine3.14"
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=seba
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=postgres
    volumes:
     - nps_data:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build:
      context: ./backend/
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=seba
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
  fronted:
    container_name: fronted
    restart: always
    build:
      context: ./fronted/app/
    ports:
      - "80:3000"
    depends_on:
      - node_app

volumes:
 nps_data: {}



